<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>lector_de_libros</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>J Reader</AssemblyName>
    <AssemblyTitle>J Reader</AssemblyTitle>
    <Product>J Reader</Product>
    <Description>Lector de libros accesible para EPUB y PDF, pensado para lectores de pantalla como NVDA.</Description>
    <Version>0.1.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="VersOne.Epub" Version="3.3.6" />
  </ItemGroup>

</Project>
